### ISSUE TITLE
Feature: Matching using alternate English Titles (and katakana?)

### ISSUE THREAD

**Issue by Mizerka** [Fribb/MyAnimeList.bundle#11]
Feature request;

Pulling series from various sources and with different naming is a pain to manage and match correctly, tvdb uses english, mal uses japanese etc.

Matching by both mal titles and english alternate would be very welcome addition.

**Comment by Fribb** [comment]
The Agent doesn't match by name on TheTVDB but rather pulls the mapping between MAL and TheTVDB from [another project](https://github.com/Fribb/anime-lists) of mine and requests the Image files directly with that ID, there is nothing more pulled from TheTVDB other than the images.

The program that creates those mapping lists actually uses any available title on MAL and takes the one that was got the most "hits" on TheTVDB.

Therefore there is no need for the MAL Agent to do this on its own.

However, If the mappings are wrong, the list needs to be corrected. Currently, my program is not running to update the lists automatically so newer or upcoming shows might miss the images and I only have time to look at it next month.
