### ISSUE TITLE
Use MAL ID for series search

### ISSUE THREAD

**Issue by EZarnosky** [Fribb/MyAnimeList.bundle#17]
There are times it is a pain getting the name right in the search. It would be welcome feature to be able to enter "MAL:154" to search for a specific match (154 is Shaman King - https://myanimelist.net/anime/154/Shaman_King)

**Comment by Fribb** [comment]
This has been implemented in [this commit](https://github.com/Fribb/MyAnimeList.bundle/commit/b2b853644588b2a3a209a970756277af1acf84f2)

use "myanimelist-id:<theID>" to match it for a specific myanimelist ID.
