### ISSUE TITLE
Your Changes could not be saved.

### ISSUE THREAD

**Issue by Kiaos** [Fribb/MyAnimeList.bundle#2]
When selecting the agent either durring adding the library in advanced or while doing an edit it will not allow me to use MyAnimeList.net Agent and will say "Your changes could not be saved." when hitting save changes button. This is on latest version of plex server 1.9.2.4285. It doesn't matter which scanner I use it still wont let me save the changes.

![addnosave](https://user-images.githubusercontent.com/32118932/31111372-d0932e94-a7ca-11e7-9c48-35467a9cacb3.png)

![nosave](https://user-images.githubusercontent.com/32118932/31111334-825d73ce-a7ca-11e7-8ebf-1956c16f66aa.png)

**Comment by Fribb** [comment]
If you are running Plex on a Linux based OS then you might need to set the permissions correctly which was suggested by another user [here](https://forums.plex.tv/discussion/comment/1425234/#Comment_1425234). When you are running windows instead I couldn't figure out a way why this is happening yet. But you can try [this](http://forums.plex.tv/discussion/comment/1465546/#Comment_1465546) and [this](http://forums.plex.tv/discussion/comment/1488680/#Comment_1488680)

**Comment by frrk** [comment]
I'd been struggling to fix this on Windows 10. Going through every file and folder, to check permissions.

Turns out I just had to restart the Plex server. I did not shut down Plex while installing the plug-in.

**Comment by rmnpch** [comment]
worked for me when I closed it and chose to run as admin
