### ISSUE TITLE
Series Will Not Appear - "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e" - Max Length Issue?

### ISSUE THREAD

**Issue by ScottDennison** [Fribb/MyAnimeList.bundle#21]
The following MAL refuses to be matched (the correct show does not appear in the search results)
https://myanimelist.net/anime/40496/Maou_Gakuin_no_Futekigousha__Shijou_Saikyou_no_Maou_no_Shiso_Tensei_shite_Shison-tachi_no_Gakkou_e

This even refuses to show any matches when using my long-since-merged pull-request #10 feature and specifiyng the search string of myanimelist-id:40496

I'm assuming the extra long title is overflowing some field's max length?

**Comment by Fribb** [comment]
> I'm assuming the extra long title is overflowing some field's max length?

I would imagine that this would be visible in the log files? 

Taking the Name and [searching over the API](https://atarashii.fribbtastic.net/web/2.1/anime/search?q=Maou%20Gakuin%20no%20Futekigousha:%20Shijou%20Saikyou%20no%20Maou%20no%20Shiso,%20Tensei%20shite%20Shison-tachi%20no%20Gakkou%20e) does give a search result.

I just tried to use `myanimelist-id:40496` in the manual search and it works for me.

**Comment by ScottDennison** [comment]
I've since corrected the myanimelist-id:40496 issue.
That was my bad.
Back when the atarashii API was resulting in internal server errors for every request to /anime/{id}, I created a small web server that used a reverse engineered version of the new MAL api to return results in the same JSON format. That hadn't come back up upon server restart. I've switched back to using atarashii API now that it is fixed.

Good point with regards to the log files.
It calls https://atarashii.fribbtastic.net/web/2.1/anime/search?q=Maou+Gakuin+No+Futekigousha+Shijou+Saikyou+No+Maou+No+Shiso%2C+Tensei+Shite+Shison+Tachi+No+Gakkou+E+Kayou
Which results in a 404 with response body
{"error":"not-found"}

**Comment by Fribb** [comment]
> Which then makes me wonder where on earth the extra Kayou on the end comes from - It's not in the filename, nor in the MAL title, nor did I manually type it in.

That is indeed weird, the value that will be used for the search is the name of the show which is provided by the scanner (which also doesn't take it just 1:1) so maybe you had the filename that way at some point but was corrected after that?
