### ISSUE TITLE
Api does not return response

### ISSUE THREAD

**Issue by zanclo** [Fribb/MyAnimeList.bundle#25]
For a few days, the API has not responded to requests to identify some series and the manual search does not work either. Do you know why this is?

I attach a screenshot of the Plex log
[Captura](https://user-images.githubusercontent.com/90968750/133889217-875d97e8-d3f1-4f9f-8e54-f541d05b4b9e.PNG)

Thanks!

**Comment by Fribb** [comment]
Did you update to version 7.0.0? 

The new version uses a new API as the backend, one that is actually being maintained and developed further, the old API is disabled and will not be used anymore.

**Comment by zanclo** [comment]
yes, i did  a few days ago.

**Comment by Fribb** [comment]
I will need the Agent log files to be able to say more clearly what is going on

**Comment by zanclo** [comment]
problem solved. Plex was not using version 7.0.0.
Everything is working now.
Thank you very much and sorry for the inconvenience
