### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by linkinstreet** [Fribb/MyAnimeList.bundle#26]
Hi. 

I am having some issues with Myanimelist bundle for the past few weeks. For whatever reason, I can't seem to get a match anymore. 

Today for example
`Sep 21, 2021 07:23:33.539 [7848] DEBUG - Issuing search query: http://127.0.0.1:32400/system/agents/search?mediaType=2&id=82222&identifier=net.fribbtastic.coding.plex.myanimelist&duration=373516&episodic=1&filename=%255C%255Cxeone52650%255Canime%2520ongoing%255CGanbare%2520Douki-chan%255C%255BSubsPlease%255D%2520Ganbare%2520Douki-chan%2520-%252001%2520%25281080p%2529%2520%255B9FA71CB5%255D%252Emkv&lang=en&openSubtitlesHash=1af27a8e6b751144&plexHash=15e39864abee4b89f4b4f0d38fa775cb8501cfb3&episode=1&episodic=1&season=1&show=Ganbare%20Douki%20Chan&manual=1`
`Sep 21, 2021 07:23:33.539 [7848] DEBUG - HTTP requesting GET http://127.0.0.1:32400/system/agents/search?mediaType=2&id=82222&identifier=net.fribbtastic.coding.plex.myanimelist&duration=373516&episodic=1&filename=%255C%255Cxeone52650%255Canime%2520ongoing%255CGanbare%2520Douki-chan%255C%255BSubsPlease%255D%2520Ganbare%2520Douki-chan%2520-%252001%2520%25281080p%2529%2520%255B9FA71CB5%255D%252Emkv&lang=en&openSubtitlesHash=1af27a8e6b751144&plexHash=15e39864abee4b89f4b4f0d38fa775cb8501cfb3&episode=1&episodic=1&season=1&show=Ganbare%20Douki%20Chan&manual=1`
`Sep 21, 2021 07:23:33.540 [9932] DEBUG - Request: [127.0.0.1:59600 (Loopback)] GET /system/agents/search?mediaType=2&id=82222&identifier=net.fribbtastic.coding.plex.myanimelist&duration=373516&episodic=1&filename=%255C%255Cxeone52650%255Canime%2520ongoing%255CGanbare%2520Douki-chan%255C%255BSubsPlease%255D%2520Ganbare%2520Douki-chan%2520-%252001%2520%25281080p%2529%2520%255B9FA71CB5%255D%252Emkv&lang=en&openSubtitlesHash=1af27a8e6b751144&plexHash=15e39864abee4b89f4b4f0d38fa775cb8501cfb3&episode=1&episodic=1&season=1&show=Ganbare%20Douki%20Chan&manual=1 (21 live) GZIP Signed-in / Accept => */* / Accept-Encoding => gzip / Host => 127.0.0.1:32400 / User-Agent => PlexMediaServer/1.24.2.4973-2b1b51db9`
`Sep 21, 2021 07:23:33.540 [9932] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/agents/search?mediaType=2&id=82222&identifier=net.fribbtastic.coding.plex.myanimelist&duration=373516&episodic=1&filename=%255C%255Cxeone52650%255Canime%2520ongoing%255CGanbare%2520Douki-chan%255C%255BSubsPlease%255D%2520Ganbare%2520Douki-chan%2520-%252001%2520%25281080p%2529%2520%255B9FA71CB5%255D%252Emkv&lang=en&openSubtitlesHash=1af27a8e6b751144&plexHash=15e39864abee4b89f4b4f0d38fa775cb8501cfb3&episode=1&episodic=1&season=1&show=Ganbare%20Douki%20Chan&manual=1`
`Sep 21, 2021 07:23:33.540 [9932] DEBUG - HTTP requesting GET http://127.0.0.1:59485/system/agents/search?mediaType=2&id=82222&identifier=net.fribbtastic.coding.plex.myanimelist&duration=373516&episodic=1&filename=%255C%255Cxeone52650%255Canime%2520ongoing%255CGanbare%2520Douki-chan%255C%255BSubsPlease%255D%2520Ganbare%2520Douki-chan%2520-%252001%2520%25281080p%2529%2520%255B9FA71CB5%255D%252Emkv&lang=en&openSubtitlesHash=1af27a8e6b751144&plexHash=15e39864abee4b89f4b4f0d38fa775cb8501cfb3&episode=1&episodic=1&season=1&show=Ganbare%20Douki%20Chan&manual=1`
`Sep 21, 2021 07:26:00.432 [11012] ERROR - Timeout or error reading status line from plug-in pipe [net.fribbtastic.coding.plex.myanimelist], we're killing it.`

I am using version 7.0 with Plex version 1.24.2.4973. I wonder if an update broke this plugin.

**Comment by Fribb** [comment]
That seems to be the output of the console of plex which doesn't really help me. I would need the log files from the agent.

You will find the log files in your Plex config folder `Library\Application Support\Plex Media Server\Logs\PMS Plugin Logs\net.fribbtastic.coding.plex.myanimelist.log`

Be aware that this might not need to be a "bug" but rather that there are too many requests happening from the API to MyAnimeList and MyAnimeList is then blocking it. The API has a caching system but that cache has to be built first.

Still, I would need the log file to make sure that this is actually the reason.

**Comment by linkinstreet** [comment]
https://pastebin.com/cK2pKNcy

Hmm, seems that this might be the culprit: NameError: name 'CommonUtils' is not defined, which is weird, as the plugin was working fine before

**Comment by Fribb** [comment]
Can you try reinstalling the agent? Please make sure that you delete the previous version completely and not just overwriting everything.

**Comment by linkinstreet** [comment]
I deleted the plugin, restarted the server, re-added the plugin and then restarted the server again. Seems to be working for now, as no error message appears in the log file like earlier. 

Thank you
