### ISSUE TITLE
Directions to self-host jikan api

### ISSUE THREAD

**Issue by fatflyingpigs** [Fribb/MyAnimeList.bundle#33]
I'd like to use this agent purely self-hosted. The readme states "The accessed Jikan API is running on my own server ... "
Does this mean that "https://api.jikan.moe" is your site? If we replace that url in jikan.py with our own self hosted path, would that suffice?

Also a suggestion: Add some instructions in the readme & a config file so others can opt to self host jikan as well.

**Comment by Fribb** [comment]
In #32 the API endpoints changed with version v7.0.3 in which the previously used self-hosted version got replaced with the current official jikan endpoints.

All the documentation for the Jikan API are readily available for you to use to create your own instance of the Jikan API: https://jikan.moe/ 

However, I will not provide any instructions or anything like that to self-host the API. The Agent is meant to run the way it is in the currently up-to-date code. When you want to host this yourself you need to change the codebase and create a fork of the project.

And I cannot provide any support for forked projects. By using your own self-hosted version of the Jikan API you are introducing something that I have no influence on in terms of reproducibility. With the official API and my own self-hosted instance, I could always verify if that Bug report was an API or Agent issue. With a self-hosted API version that is probably not even accessible for me, I will not be able to do that anymore.

Using the Agent with your own self-hosted version of the API is out of the scope of support I can provide.
