### ISSUE TITLE
add myanimelist guid matching from scanner.

### ISSUE THREAD

**Issue by Fribb** [Fribb/MyAnimeList.bundle#35]
based on the feature request in ZeroQI/Absolute-Series-Scanner#407 this would need to be implemented and supported in the Agent as well. to make this uniform the manual match should be replaced with the new way.

**Comment by ZeroQI** [comment]
Support added now
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/7e61717d8c82d203754ed8cd90976d99185f8783
