### ISSUE TITLE
 Producer values being put into Studio Metadata

### ISSUE THREAD

**Issue by ghost** [Fribb/MyAnimeList.bundle#4]
In this block of code (lines 407-417),
```
# get the producers if they are available
    tmp_producers = getJSONValue("producers", jsonResponse)
    Log.Debug("Producers: " + str(tmp_producers))
    if tmp_producers is not None and len(tmp_producers) > 0:
        apiAnimeProducers = ""
        for idx, producer in enumerate(tmp_producers):
            apiAnimeProducers += str(producer)
            if idx < len(tmp_producers)-1:
                apiAnimeProducers += ", "
        
        metadata.studio = str(apiAnimeProducers)
```
The producer values are being inserted into Plex's studio metadata, which is usually not the same as the studio values, and then shows up in the show's page on Plex. For example, if you were to grab the metadata for [Bakemonogatari](https://myanimelist.net/anime/5081/Bakemonogatari), the Producers are Aniplex and Kodansha, and the Studio is Shaft. The above code is taking Aniplex and Kodansha and putting them as the Studios. As far as I know, there isn't a spot for Producer metadata in Plex.

Strangely enough, [it doesn't seem like the atarashii API even grabs the studio values](https://atarashii.fribbtastic.net/web/2.1/anime/5081).

**Comment by Fribb** [comment]
While technically this is correct I will leave it that way for now. Atarashii is, as you say, not providing any Studio information and Plex doesn't offer a place to save the Producers in the metadata, which means there would be some Information loss.

When MyAnimeList releases their official API (and provides all the necessary information in it) this could and should be changed.
