### ISSUE TITLE
Add Plugins support 

### ISSUE THREAD

**Issue by Mizerka** [Fribb/MyAnimeList.bundle#8]
Mostly for things like Sub-Zero subs which I trust a lot more to pull and keep subs up to date.

**Comment by Fribb** [comment]
You can add "com.plexapp.agents.subzero" in the __init__.py in line 23 under AGENT_ACCEPTS_FROM

Can you try and give me feedback how it works? I don't use subzero and cant say how it should behave. If that works already then I can add it natively

**Comment by Mizerka** [comment]
Added in, restarted service and now appears under subzero, I will test functionality to make sure but appears to be fine so far.
![image](https://user-images.githubusercontent.com/45487386/55400307-6826fa00-5545-11e9-9e81-dbf6d70950cc.png)

**Comment by Mizerka** [comment]
Sorry for delay, been a busy week;

I can confirm this is now working as intended, was hard to get examples because of either lack of misc languages to pull or vids without embedded mkv subs which I ignore.

Thanks
